name: linux_can
description: Dart implementation of SocketCAN.
version: 0.1.1
author: matzesoft

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.0.0


