name: linux_can
description: Dart implementation of SocketCAN.
version: 0.1.4

environment:
  sdk: ">=3.0.0"

dependencies:
  ffi: ^2.0.2
  posix: ^5.0.0
  build_cli_annotations: ^2.0.0

dev_dependencies:
  build_cli: ^2.0.0
  build_runner: ^2.0.6


executables:
  candump: candump
